In [1]:
import cv2
import numpy as np
import os
import torch
from torchvision import transforms,models,datasets
import torchvision

torch.cuda.empty_cache()

In [2]:
class_names=['Dhruv', 'Devansh', 'Urmila']
device=torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')

In [3]:
face_cascade = cv2.CascadeClassifier("C:/Users/hp/Desktop/Capstone/haarcascade_frontalface_default.xml")
model = torchvision.models.resnet18(num_classes=len(class_names)).eval().to(device)
model.load_state_dict(torch.load('model_weights.pth'))

<All keys matched successfully>

In [4]:
def face_extractor(img):
    global cropped_face
    faces = face_cascade.detectMultiScale(img, 1.3, 5)
    if faces is ():
        return None

    for (x,y,w,h) in faces:
        cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,255),2)
        cropped_face = img[y:y+h, x:x+w]

    return cropped_face

<>:4: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:4: SyntaxWarning: "is" with a literal. Did you mean "=="?
<ipython-input-4-16974e392518>:4: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if faces is ():


In [5]:
transform=transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])

In [29]:
# video_capture = cv2.VideoCapture(0)
# while True:
#     _, frame = video_capture.read()
    
#     face=face_extractor(frame)
#     if type(face) is np.ndarray:
#         face = cv2.resize(face, (224, 224))
#         frames=transform(face)
#         print(frames)
#         frames=torch.unsqueeze(frames,0)
#         print(frames.size())
#         output=model(frames)
#         print(output)
#         _,preds=torch.max(output,1)
#         print(preds)
#         print(class_names[preds])
#         cv2.putText(frame,class_names[preds], (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
#     else:
#         cv2.putText(frame,"No face found", (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
#     cv2.imshow('Video', frame)
# #     print(frame)
#     if cv2.waitKey(1) & 0xFF == ord('q'):
#         break
# video_capture.release()
# cv2.destroyAllWindows()

tensor([[[-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179],
         [-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179],
         [-2.1179, -2.1179, -1.6042,  ..., -1.3644, -1.5357, -2.1179],
         ...,
         [-2.1179, -2.1179, -1.0904,  ...,  0.3823, -0.4911, -2.1179],
         [-2.1179, -2.1179, -1.4329,  ..., -0.4739, -1.0562, -2.1179],
         [-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179]],

        [[ 2.4286,  2.4286,  2.4286,  ...,  2.4286,  2.4286,  2.4286],
         [ 2.4286,  2.4286,  2.4286,  ...,  2.4286,  2.4286,  2.4286],
         [ 2.4286,  2.4286,  2.1660,  ...,  1.2731,  1.7633,  2.4286],
         ...,
         [ 2.4286,  2.4286,  1.5882,  ...,  0.3978,  1.1155,  2.4286],
         [ 2.4286,  2.4286,  1.8859,  ...,  1.1155,  1.5707,  2.4286],
         [ 2.4286,  2.4286,  2.4286,  ...,  2.4286,  2.4286,  2.4286]],

        [[ 2.6400,  2.6400,  2.6400,  ...,  2.6400,  2.6400,  2.6400],
         [ 2.6400,  2.6400,  2.6400,  ...,  2

tensor([[ 2.4938,  1.0817, -2.2640]], grad_fn=<AddmmBackward>)
tensor([0])
Dhruv
tensor([[[-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179],
         [-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179],
         [-2.1179, -2.1179, -1.6555,  ..., -1.1760, -1.5185, -2.1179],
         ...,
         [-2.1179, -2.1179, -1.0562,  ...,  0.3138, -0.5767, -2.1179],
         [-2.1179, -2.1179, -1.4329,  ..., -0.5596, -1.1247, -2.1179],
         [-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179]],

        [[ 2.4286,  2.4286,  2.4286,  ...,  2.4286,  2.4286,  2.4286],
         [ 2.4286,  2.4286,  2.4286,  ...,  2.4286,  2.4286,  2.4286],
         [ 2.4286,  2.4286,  2.1835,  ...,  1.6057,  1.9034,  2.4286],
         ...,
         [ 2.4286,  2.4286,  1.6933,  ...,  0.3978,  1.1331,  2.4286],
         [ 2.4286,  2.4286,  1.9734,  ...,  1.1331,  1.6057,  2.4286],
         [ 2.4286,  2.4286,  2.4286,  ...,  2.4286,  2.4286,  2.4286]],

        [[ 2.6400,  2.6400,  2.6400

tensor([[ 2.2982,  1.3031, -2.4961]], grad_fn=<AddmmBackward>)
tensor([0])
Dhruv
tensor([[[-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179],
         [-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179],
         [-2.1179, -2.1179, -1.9980,  ..., -1.6384, -1.8782, -2.1179],
         ...,
         [-2.1179, -2.1179, -1.5528,  ...,  0.3823, -0.7993, -2.1179],
         [-2.1179, -2.1179, -1.8268,  ..., -0.8164, -1.4329, -2.1179],
         [-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179]],

        [[ 2.4286,  2.4286,  2.4286,  ...,  2.4286,  2.4286,  2.4286],
         [ 2.4286,  2.4286,  2.4286,  ...,  2.4286,  2.4286,  2.4286],
         [ 2.4286,  2.4286,  2.3585,  ...,  1.9909,  2.2010,  2.4286],
         ...,
         [ 2.4286,  2.4286,  2.0609,  ...,  0.3978,  1.3606,  2.4286],
         [ 2.4286,  2.4286,  2.2360,  ...,  1.3606,  1.8683,  2.4286],
         [ 2.4286,  2.4286,  2.4286,  ...,  2.4286,  2.4286,  2.4286]],

        [[ 2.6400,  2.6400,  2.6400

tensor([[ 3.2592,  1.3798, -3.0051]], grad_fn=<AddmmBackward>)
tensor([0])
Dhruv
tensor([[[-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179],
         [-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179],
         [-2.1179, -2.1179, -2.1008,  ..., -1.9809, -2.0494, -2.1179],
         ...,
         [-2.1179, -2.1179, -1.9809,  ...,  0.3309, -1.0562, -2.1179],
         [-2.1179, -2.1179, -2.0665,  ..., -1.0562, -1.6555, -2.1179],
         [-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179]],

        [[ 2.4286,  2.4286,  2.4286,  ...,  2.4286,  2.4286,  2.4286],
         [ 2.4286,  2.4286,  2.4286,  ...,  2.4286,  2.4286,  2.4286],
         [ 2.4286,  2.4286,  2.4286,  ...,  2.3060,  2.3761,  2.4286],
         ...,
         [ 2.4286,  2.4286,  2.2710,  ...,  0.4853,  1.5707,  2.4286],
         [ 2.4286,  2.4286,  2.3585,  ...,  1.5707,  2.0609,  2.4286],
         [ 2.4286,  2.4286,  2.4286,  ...,  2.4286,  2.4286,  2.4286]],

        [[ 2.6400,  2.6400,  2.6400

tensor([[[-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179],
         [-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179],
         [-2.1179, -2.1179, -1.9124,  ..., -0.7308, -1.2959, -2.1179],
         ...,
         [-2.1179, -2.1179, -1.4843,  ...,  0.6734, -0.4568, -2.1179],
         [-2.1179, -2.1179, -1.7412,  ..., -0.4568, -1.1418, -2.1179],
         [-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179]],

        [[ 2.4286,  2.4286,  2.4286,  ...,  2.4286,  2.4286,  2.4286],
         [ 2.4286,  2.4286,  2.4286,  ...,  2.4286,  2.4286,  2.4286],
         [ 2.4286,  2.4286,  2.1660,  ...,  2.4111,  2.4286,  2.4286],
         ...,
         [ 2.4286,  2.4286,  1.6232,  ...,  0.8179,  1.4832,  2.4286],
         [ 2.4286,  2.4286,  1.9384,  ...,  1.4657,  1.8683,  2.4286],
         [ 2.4286,  2.4286,  2.4286,  ...,  2.4286,  2.4286,  2.4286]],

        [[ 2.6400,  2.6400,  2.6400,  ...,  2.6400,  2.6400,  2.6400],
         [ 2.6400,  2.6400,  2.6400,  ...,  2

torch.Size([1, 3, 224, 224])
tensor([[ 3.3877,  1.6562, -2.7775]], grad_fn=<AddmmBackward>)
tensor([0])
Dhruv
tensor([[[-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179],
         [-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179],
         [-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179],
         ...,
         [-2.1179, -2.1179, -2.1179,  ..., -1.0048, -1.8097, -2.1179],
         [-2.1179, -2.1179, -2.1179,  ..., -1.8097, -2.0323, -2.1179],
         [-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179]],

        [[ 2.4286,  2.4286,  2.4286,  ...,  2.4286,  2.4286,  2.4286],
         [ 2.4286,  2.4286,  2.4286,  ...,  2.4286,  2.4286,  2.4286],
         [ 2.4286,  2.4286,  2.4286,  ...,  2.4286,  2.4286,  2.4286],
         ...,
         [ 2.4286,  2.4286,  2.4286,  ...,  1.8158,  2.2535,  2.4286],
         [ 2.4286,  2.4286,  2.4286,  ...,  2.2535,  2.3761,  2.4286],
         [ 2.4286,  2.4286,  2.4286,  ...,  2.4286,  2.4286,  2.4286]],

      

tensor([[ 3.5791,  1.4490, -2.8466]], grad_fn=<AddmmBackward>)
tensor([0])
Dhruv
tensor([[[-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179],
         [-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179],
         [-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179],
         ...,
         [-2.1179, -2.1179, -2.1179,  ..., -0.9705, -1.8097, -2.1179],
         [-2.1179, -2.1179, -2.1179,  ..., -1.8097, -2.0323, -2.1179],
         [-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179]],

        [[ 2.4286,  2.4286,  2.4286,  ...,  2.4286,  2.4286,  2.4286],
         [ 2.4286,  2.4286,  2.4286,  ...,  2.4286,  2.4286,  2.4286],
         [ 2.4286,  2.4286,  2.4286,  ...,  2.4286,  2.4286,  2.4286],
         ...,
         [ 2.4286,  2.4286,  2.4286,  ...,  1.9384,  2.2885,  2.4286],
         [ 2.4286,  2.4286,  2.4286,  ...,  2.2885,  2.3936,  2.4286],
         [ 2.4286,  2.4286,  2.4286,  ...,  2.4286,  2.4286,  2.4286]],

        [[ 2.6400,  2.6400,  2.6400

tensor([[[-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179],
         [-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179],
         [-2.1179, -2.1179, -1.3644,  ..., -0.5253, -0.9705, -2.1179],
         ...,
         [-2.1179, -2.1179, -0.6109,  ...,  0.6392, -0.1314, -2.1179],
         [-2.1179, -2.1179, -1.0219,  ..., -0.0972, -0.6623, -2.1179],
         [-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179]],

        [[ 2.4286,  2.4286,  2.4286,  ...,  2.4286,  2.4286,  2.4286],
         [ 2.4286,  2.4286,  2.4286,  ...,  2.4286,  2.4286,  2.4286],
         [ 2.4286,  2.4286,  1.9034,  ...,  1.7108,  1.8859,  2.4286],
         ...,
         [ 2.4286,  2.4286,  1.5182,  ...,  0.5378,  1.0105,  2.4286],
         [ 2.4286,  2.4286,  1.7633,  ...,  1.0630,  1.4132,  2.4286],
         [ 2.4286,  2.4286,  2.4286,  ...,  2.4286,  2.4286,  2.4286]],

        [[ 2.6400,  2.6400,  2.6400,  ...,  2.6400,  2.6400,  2.6400],
         [ 2.6400,  2.6400,  2.6400,  ...,  2

tensor([[[-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179],
         [-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179],
         [-2.1179, -2.1179, -1.7240,  ..., -1.0562, -1.4500, -2.1179],
         ...,
         [-2.1179, -2.1179, -1.0733,  ...,  0.5193, -0.4739, -2.1179],
         [-2.1179, -2.1179, -1.4672,  ..., -0.4739, -1.0904, -2.1179],
         [-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179]],

        [[ 2.4286,  2.4286,  2.4286,  ...,  2.4286,  2.4286,  2.4286],
         [ 2.4286,  2.4286,  2.4286,  ...,  2.4286,  2.4286,  2.4286],
         [ 2.4286,  2.4286,  2.2010,  ...,  1.8158,  2.0434,  2.4286],
         ...,
         [ 2.4286,  2.4286,  1.7983,  ...,  0.3803,  1.1506,  2.4286],
         [ 2.4286,  2.4286,  2.0434,  ...,  1.1506,  1.6232,  2.4286],
         [ 2.4286,  2.4286,  2.4286,  ...,  2.4286,  2.4286,  2.4286]],

        [[ 2.6400,  2.6400,  2.6400,  ...,  2.6400,  2.6400,  2.6400],
         [ 2.6400,  2.6400,  2.6400,  ...,  2

torch.Size([1, 3, 224, 224])
tensor([[ 2.3648,  0.9853, -2.2035]], grad_fn=<AddmmBackward>)
tensor([0])
Dhruv
tensor([[[-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179],
         [-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179],
         [-2.1179, -2.1179, -1.2445,  ...,  0.1939, -0.4397, -2.1179],
         ...,
         [-2.1179, -2.1179, -0.5596,  ...,  0.5536, -0.1657, -2.1179],
         [-2.1179, -2.1179, -0.9877,  ..., -0.1828, -0.6965, -2.1179],
         [-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179]],

        [[ 2.4286,  2.4286,  2.4286,  ...,  2.4286,  2.4286,  2.4286],
         [ 2.4286,  2.4286,  2.4286,  ...,  2.4286,  2.4286,  2.4286],
         [ 2.4286,  2.4286,  1.9384,  ...,  2.2885,  2.3235,  2.4286],
         ...,
         [ 2.4286,  2.4286,  1.5182,  ...,  0.3803,  0.9230,  2.4286],
         [ 2.4286,  2.4286,  1.7633,  ...,  0.9230,  1.3256,  2.4286],
         [ 2.4286,  2.4286,  2.4286,  ...,  2.4286,  2.4286,  2.4286]],

      

In [6]:
video_capture = cv2.VideoCapture(0)
count=0
while True:
    _,frame = video_capture.read()
    '''Extract face , convert to grayscale and save it in out folders'''
    if face_extractor(frame) is not None:
        count += 1
        face = cv2.resize(face_extractor(frame), (244, 244))
        face = cv2.cvtColor(face, cv2.COLOR_BGR2GRAY)
        file_name_path = 'C:/Users/hp/Desktop/Pytorch/buffer/' + str(count) + '.jpg'

        cv2.imwrite(file_name_path, face)
        cv2.putText(face, str(count), (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0, 255, 0), 2)
        cv2.imshow('Face Cropper', face)
    else:
        print("Face not found")
        pass
    if cv2.waitKey(1) == 13 or count == 100:
        break
video_capture.release()
cv2.destroyAllWindows()

In [101]:
data_dir='C:/Users/hp/Desktop/Pytorch/buffer/'
buffer_data=datasets.ImageFolder(data_dir,transform=transform)
buffer_loader=torch.utils.data.DataLoader(buffer_data,batch_size=4)


In [102]:
buffer_loader

In [103]:
for i, (inputs, labels) in enumerate(buffer_loader):
#     print(labels)
    inputs = inputs.to(device)
#     labels = labels.to(device)
    print(inputs.size())
    outputs = model(inputs)
    print(outputs)
    _, preds = torch.max(outputs, 1)
    print(preds)
    print(class_names[preds])


torch.Size([4, 3, 244, 244])


RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 2.00 GiB total capacity; 1.13 GiB already allocated; 0 bytes free; 1.14 GiB reserved in total by PyTorch)