In [1]:
import pandas as pd
import numpy as np
from sklearn.decomposition import TruncatedSVD

In [2]:
df=pd.read_csv('Book 1.csv')
df   

In [4]:
ratings_utility_matrix = df.pivot_table(values='rating', index='user_id', columns='product_id', fill_value=0)
ratings_utility_matrix# This is done because n>>m in real life. 

product_id  1   2   3   4   6   9   11  21
user_id                                   
0            1   2   3   0   0   0   0   0
1            0   0   0   0   1   5   4   4
2            0   0   2   5   0   0   0   0

In [7]:
X = ratings_utility_matrix.T
X

user_id     0  1  2
product_id         
1           1  0  0
2           2  0  0
3           3  0  2
4           0  0  5
6           0  1  0
9           0  5  0
11          0  4  0
21          0  4  0

In [8]:
SVD = TruncatedSVD(n_components=2)#
decomposed_matrix = SVD.fit_transform(X)
decomposed_matrix

array([[ 0.00000000e+00,  3.31006941e-01],
       [ 0.00000000e+00,  6.62013883e-01],
       [-2.22044605e-15,  2.88027746e+00],
       [-5.55111512e-15,  4.71814160e+00],
       [ 1.00000000e+00,  9.99200722e-16],
       [ 5.00000000e+00,  4.99600361e-15],
       [ 4.00000000e+00,  3.99680289e-15],
       [ 4.00000000e+00,  3.99680289e-15]])

In [21]:
correlation_matrix = np.corrcoef(decomposed_matrix)
correlation_matrix

array([[ 1.        ,  1.        ,  0.75592895, -0.5       , -0.5       ,
        -0.5       , -0.5       , -0.5       ],
       [ 1.        ,  1.        ,  0.75592895, -0.5       , -0.5       ,
        -0.5       , -0.5       , -0.5       ],
       [ 0.75592895,  0.75592895,  1.        ,  0.18898224, -0.94491118,
        -0.94491118, -0.94491118, -0.94491118],
       [-0.5       , -0.5       ,  0.18898224,  1.        , -0.5       ,
        -0.5       , -0.5       , -0.5       ],
       [-0.5       , -0.5       , -0.94491118, -0.5       ,  1.        ,
         1.        ,  1.        ,  1.        ],
       [-0.5       , -0.5       , -0.94491118, -0.5       ,  1.        ,
         1.        ,  1.        ,  1.        ],
       [-0.5       , -0.5       , -0.94491118, -0.5       ,  1.        ,
         1.        ,  1.        ,  1.        ],
       [-0.5       , -0.5       , -0.94491118, -0.5       ,  1.        ,
         1.        ,  1.        ,  1.        ]])

In [22]:
product_names = list(X.index)
product_ID = product_names.index(2)
product_ID,product_names

(1, [1, 2, 3, 4, 6, 9, 11, 21])

In [23]:
i =1

product_names = list(X.index)
product_ID = product_names.index(i)
X.index

Int64Index([1, 2, 3, 4, 6, 9, 11, 21], dtype='int64', name='product_id')

In [24]:
correlation_product_ID = correlation_matrix[product_ID]
correlation_product_ID

array([ 1.        ,  1.        ,  0.75592895, -0.5       , -0.5       ,
       -0.5       , -0.5       , -0.5       ])

In [25]:
Recommend = list(X.index[correlation_product_ID > 0.90])

# Removes the item already bought by the customer
Recommend.remove(i) 

Recommend[0:5]

[2]

In [20]:
X.index[correlation_product_ID > 0.90]

Int64Index([1, 2, 3, 4], dtype='int64', name='product_id')